name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup cross
      run: sudo dpkg --add-architecture arm64 && sudo apt update

    - name: Install dependencies
      run: sudo apt install libsecret-1-dev:arm64 gcc-aarch64-linux-gnu

    - name: build-nogui
      env:
        GOOS: "linux"
        GOARCH: "arm64"
      run: make build-nogui
